CREATE TABLE "HR"."BOARD3" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENTS" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"WRITEDATE" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEWCOUNT" NUMBER(38,0)
   )
   
ALTER TABLE BOARD3 MODIFY WRITER VARCHAR2(200)

ALTER TABLE BOARD3 DROP COLUMN VIEWCOUNT

ALTER TABLE BOARD3 ADD TES varchar2(100)

DROP TABLE BBS2  





CREATE USER apple IDENTIFIED BY a1234 

GRANT CONNECT, resource, dba TO apple 

CREATE TABLE "HR"."PRODUCT222" 
   (	"ID" VARCHAR2(100) PRIMARY key, 
	"NAME" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"PRICE" NUMBER(38,0)
   )

 
 INSERT INTO MEMBER VALUES ('100','100','park','011')

INSERT INTO MEMBER VALUES ('200','200','park','011')

INSERT INTO MEMBER VALUES ('300','300','park','011')

SELECT * FROM "MEMBER" m 

SELECT * FROM "MEMBER" m  WHERE  ID  = '100'


SELECT id FROM "MEMBER" m  WHERE  ID  = '100'

SELECT id, PW  FROM "MEMBER" m  WHERE  ID  = '100'

SELECT id as name FROM "MEMBER" m  WHERE  ID  = '100'


UPDATE "MEMBER" SET NAME ='kim' WHERE id='100'

UPDATE "MEMBER" SET NAME ='yam' WHERE id='200'

UPDATE "MEMBER" SET NAME ='lee' WHERE id='300'

UPDATE "MEMBER" SET tel = '999' WHERE id='ice'

DELETE FROM "MEMBER" m WHERE ID = '100'

DELETE FROM "MEMBER" m WHERE TEL ='011'

SELECT * FROM "MEMBER" m WHERE ID ='200' AND TEL ='011'

SELECT * FROM "MEMBER" m WHERE ID ='200' OR  TEL ='011'

CREATE TABLE PRODUCT (
	id varchar2 (200),
	name varchar2 (200),
	content varchar2 (200),
	price varchar2 (200),
	company varchar2 (200),
	img varchar2 (200)
)

SELECT * FROM "MEMBER" m ORDER BY ID  --오름차순

SELECT * FROM "MEMBER" m ORDER BY ID DESC  --내림차순
----------------------------------------------------------
SELECT * FROM PRODUCT p ORDER BY COMPANY

SELECT NAME ,IMG  FROM PRODUCT p WHERE id='100' AND PRICE = '1000'

SELECT NAME ,PRICE  FROM PRODUCT p WHERE COMPANY ='c100' 

SELECT NAME ,PRICE  FROM PRODUCT p WHERE COMPANY ='c100' OR  COMPANY ='c200'

UPDATE PRODUCT set CONTENT ='품절' WHERE PRICE = '5000'

SELECT * FROM PRODUCT p 

UPDATE PRODUCT SET IMG = '0.png' ,PRICE = '10000'WHERE id = '100' OR ID ='102'

UPDATE PRODUCT SET COMPANY= 'apple' , NAME = 'appleshoes' WHERE ID = '101'

DELETE FROM PRODUCT p WHERE NAME='shoes1' OR ID='107'

DELETE FROM PRODUCT p WHERE COMPANY = 'c100'

DELETE FROM PRODUCT p 

DROP TABLE PRODUCT 












